### ISSUE TITLE
Parallel/Pipeline creates errors

### ISSUE THREAD

**Issue by NathanielMichael** [orientechnologies/orientdb-etl#10]
I'm not sure what is causing this yet but I wanted to document it and start a discussion to perhaps expedite a solution, I'll probably dig more into this tomorrow...

~~My hypothesis is this is related to using the `merge` transformer because this doesn't happen on any of my other ETLs that do not use `merge`. I could be wrong though.~~

I was wrong. This happens when everything is removed except for `vertex` - now I believe this is caused by the UNIQUE index.

This only happens when `"parallel"` is set to `true` - if I disable parallel then this does not occur - here is what I'm seeing:

```
nate at pu in ~/Projects/releases/orientdb-community-2.0-M2/bin
$ ./oetl.sh interests.json 
OrientDB etl v.2.0-M2 (build @BUILD@) www.orientechnologies.com
BEGIN ETL PROCESSOR
Started parallel execution with 8 threads
Exception in thread "OrientDB ETL pipeline-3" com.orientechnologies.orient.etl.OETLProcessHaltedException: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #14:18 (cluster: interest)
	at com.orientechnologies.orient.etl.OETLPipeline.execute(OETLPipeline.java:130)
	at com.orientechnologies.orient.etl.OETLProcessor$2.run(OETLProcessor.java:302)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #14:18 (cluster: interest)
	at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.read(ODatabaseRaw.java:295)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.executeReadRecord(ODatabaseRecordAbstract.java:915)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:79)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.load(ODatabaseRecordTx.java:264)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.load(ODatabaseRecordTx.java:43)
	at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:302)
	at com.orientechnologies.orient.etl.transformer.OAbstractLookupTransformer.lookup(OAbstractLookupTransformer.java:102)
	at com.orientechnologies.orient.etl.transformer.OMergeTransformer.executeTransform(OMergeTransformer.java:46)
	at com.orientechnologies.orient.etl.transformer.OAbstractTransformer.transform(OAbstractTransformer.java:37)
	at com.orientechnologies.orient.etl.OETLPipeline.execute(OETLPipeline.java:108)
	... 2 more
Caused by: com.orientechnologies.common.concur.lock.OLockException: Cannot unlock a never acquired lock
	at com.orientechnologies.orient.core.tx.OTransactionAbstract.unlockRecord(OTransactionAbstract.java:123)
	at com.orientechnologies.orient.core.id.ORecordId.unlock(ORecordId.java:276)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1359)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:716)
	at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.read(ODatabaseRaw.java:288)
	... 11 more
Error in pipeline execution, retry = 1/10
Exception in thread "OrientDB ETL pipeline-4" com.orientechnologies.orient.etl.OETLProcessHaltedException: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #14:179 (cluster: interest)
	at com.orientechnologies.orient.etl.OETLPipeline.execute(OETLPipeline.java:130)
	at com.orientechnologies.orient.etl.OETLProcessor$2.run(OETLProcessor.java:302)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #14:179 (cluster: interest)
	at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.read(ODatabaseRaw.java:295)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.executeReadRecord(ODatabaseRecordAbstract.java:915)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:79)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.load(ODatabaseRecordTx.java:264)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.load(ODatabaseRecordTx.java:43)
	at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:302)
	at com.orientechnologies.orient.etl.transformer.OAbstractLookupTransformer.lookup(OAbstractLookupTransformer.java:102)
	at com.orientechnologies.orient.etl.transformer.OMergeTransformer.executeTransform(OMergeTransformer.java:46)
	at com.orientechnologies.orient.etl.transformer.OAbstractTransformer.transform(OAbstractTransformer.java:37)
	at com.orientechnologies.orient.etl.OETLPipeline.execute(OETLPipeline.java:108)
	... 2 more
Caused by: com.orientechnologies.common.concur.lock.OLockException: Cannot unlock a never acquired lock
	at com.orientechnologies.orient.core.tx.OTransactionAbstract.unlockRecord(OTransactionAbstract.java:123)
	at com.orientechnologies.orient.core.id.ORecordId.unlock(ORecordId.java:276)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1359)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:716)
	at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.read(ODatabaseRaw.java:288)
	... 11 more
Error in pipeline execution, retry = 1/10
Error in pipeline execution, retry = 1/10
Error in pipeline execution, retry = 2/10
+ extracted 10,726 records (0 records/sec) - 10,726 records -> loaded 1,354 vertices (0 vertices/sec) Total time: 1000ms [0 warnings, 0 errors]
+ extracted 10,726 records (0 records/sec) - 10,726 records -> loaded 1,354 vertices (0 vertices/sec) Total time: 2s [0 warnings, 0 errors]
^C+ extracted 10,726 records (0 records/sec) - 10,726 records -> loaded 1,354 vertices (0 vertices/sec) Total time: 3s [0 warnings, 0 errors]
.......
Exception in thread "Thread-2" com.orientechnologies.common.concur.OTimeoutException: Timeout on acquiring exclusive lock against resource of class: class com.orientechnologies.common.concur.resource.OSharedResourceAdaptiveExternal with timeout=30000
	at com.orientechnologies.common.concur.resource.OSharedResourceAdaptive.throwTimeoutException(OSharedResourceAdaptive.java:188)
	at com.orientechnologies.common.concur.resource.OSharedResourceAdaptive.acquireExclusiveLock(OSharedResourceAdaptive.java:131)
	at com.orientechnologies.common.concur.resource.OSharedResourceAdaptiveExternal.acquireExclusiveLock(OSharedResourceAdaptiveExternal.java:35)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doClose(OAbstractPaginatedStorage.java:1642)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.close(OAbstractPaginatedStorage.java:344)
	at com.orientechnologies.orient.core.storage.OStorageAbstract.close(OStorageAbstract.java:94)
	at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.close(ODatabaseRaw.java:506)
	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.close(ODatabaseWrapperAbstract.java:127)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.close(ODatabaseRecordAbstract.java:372)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.close(ODatabaseRecordTx.java:197)
	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.close(ODatabaseWrapperAbstract.java:127)
	at com.orientechnologies.orient.core.db.ODatabaseFactory.shutdown(ODatabaseFactory.java:97)
	at com.orientechnologies.orient.core.Orient.shutdown(Orient.java:200)
	at com.orientechnologies.orient.core.OrientShutdownHook.run(OrientShutdownHook.java:32)
```

Here is my configuration JSON

```json
{
  "config": {
    "verbose": false,
    "log": "info",
    "parallel": true
  },
  "extractor": {
    "jdbc": { "driver": "com.mysql.jdbc.Driver",
              "url": "jdbc:mysql://localhost/markii",
              "userName": "root",
              "userPassword": "",
              "query": "
              SELECT id, consumerProfile_id, interest_name, category_name, created_at, source_type, source_name
              FROM consumer_profile_interest
              " }
  },
  "transformers": [
    { "field": { "fieldName": "name", "expression": "interest_name" } },
    { "merge": { "joinFieldName": "interest_name", "lookup": "Interest.name" } },
    { "vertex": { "class": "Interest" } }
  ],
  "loader": {
    "orientdb": {
      "dbURL": "plocal:/Users/nate/Projects/releases/orientdb-community-2.0-M2/databases/test",
      "dbAutoCreate": true,
      "tx": false,
      "dbType": "graph",
      "dbUser": "root",
      "dbPassword": "root",
      "batchCommit": 1000,
      "wal": false,
      "indexes": [
        {"class":"Interest", "fields":["id:integer"], "type":"UNIQUE"},
        {"class":"Interest", "fields":["name:string"], "type":"UNIQUE"},
        {"class":"Category", "fields":["name:string"], "type":"UNIQUE"}
      ]
    }
  }
}
```

**Comment by stokito** [comment]
Right now I see similar error in `master` branch after running `mvn install`


```
/usr/lib/jvm/java-1.6.0-openjdk-amd64/bin/java -Dmaven.home=/opt/idea-IU-141.2.2/plugins/maven/lib/maven3 -Dclassworlds.conf=/opt/idea-IU-141.2.2/plugins/maven/lib/maven3/bin/m2.conf -Didea.launcher.port=7534 -Didea.launcher.bin.path=/opt/idea-IU-141.2.2/bin -Dfile.encoding=UTF-8 -classpath /opt/idea-IU-141.2.2/plugins/maven/lib/maven3/boot/plexus-classworlds-2.4.jar:/opt/idea-IU-141.2.2/lib/idea_rt.jar com.intellij.rt.execution.application.AppMain org.codehaus.classworlds.Launcher -Didea.version=14.1 install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building orientdb-etl 2.0.3
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ orientdb-etl ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ orientdb-etl ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 52 source files to /home/stokito/workspace/orientdb-etl/target/classes
[WARNING] /home/stokito/workspace/orientdb-etl/src/main/java/com/orientechnologies/orient/etl/OETLProcessor.java: /home/stokito/workspace/orientdb-etl/src/main/java/com/orientechnologies/orient/etl/OETLProcessor.java uses or overrides a deprecated API.
[WARNING] /home/stokito/workspace/orientdb-etl/src/main/java/com/orientechnologies/orient/etl/OETLProcessor.java: Recompile with -Xlint:deprecation for details.
[WARNING] /home/stokito/workspace/orientdb-etl/src/main/java/com/orientechnologies/orient/etl/OETLProcessor.java: Some input files use unchecked or unsafe operations.
[WARNING] /home/stokito/workspace/orientdb-etl/src/main/java/com/orientechnologies/orient/etl/OETLProcessor.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ orientdb-etl ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/stokito/workspace/orientdb-etl/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ orientdb-etl ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 8 source files to /home/stokito/workspace/orientdb-etl/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ orientdb-etl ---
[INFO] Surefire report directory: /home/stokito/workspace/orientdb-etl/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
Mar 26, 2015 9:00:21 PM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=4,070MB (heap=1,749MB os=7,867MB disk=35,062MB)
Mar 26, 2015 9:00:22 PM com.orientechnologies.common.log.OLogManager log
WARNING: {db=EdgeTransformerTest} Requested command 'create vertex type 'Person' as subclass of 'V'' must be executed outside active transaction: the transaction will be committed and reopen right after it. To avoid this behavior execute it outside a transaction
Mar 26, 2015 9:00:22 PM com.orientechnologies.common.log.OLogManager log
WARNING: {db=EdgeTransformerTest} Requested command 'create key index on 'Vertex.name'' must be executed outside active transaction: the transaction will be committed and reopen right after it. To avoid this behavior execute it outside a transaction
BEGIN ETL PROCESSOR
END ETL PROCESSOR
+ extracted 2 rows (0 rows/sec) - 2 rows -> loaded 1 vertices (0 vertices/sec) Total time: 7ms [0 warnings, 0 errors]
Mar 26, 2015 9:00:22 PM com.orientechnologies.common.log.OLogManager log
WARNING: {db=EdgeTransformerTest} Requested command 'create vertex type 'Person' as subclass of 'V'' must be executed outside active transaction: the transaction will be committed and reopen right after it. To avoid this behavior execute it outside a transaction
Mar 26, 2015 9:00:22 PM com.orientechnologies.common.log.OLogManager log
WARNING: {db=EdgeTransformerTest} Requested command 'create key index on 'Vertex.name'' must be executed outside active transaction: the transaction will be committed and reopen right after it. To avoid this behavior execute it outside a transaction
BEGIN ETL PROCESSOR
Error in Pipeline execution: com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record Person{name:Gregor}: found duplicated key 'Gregor' in index 'Person.name' previously assigned to the record #11:0 RID=#11:0
com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record Person{name:Gregor}: found duplicated key 'Gregor' in index 'Person.name' previously assigned to the record #11:0 RID=#11:0
	at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.checkEntry(OIndexTxAwareOneValue.java:221)
	at com.orientechnologies.orient.core.index.OClassIndexManager.checkIndexedPropertiesOnCreation(OClassIndexManager.java:322)
	at com.orientechnologies.orient.core.index.OClassIndexManager.checkIndexes(OClassIndexManager.java:581)
	at com.orientechnologies.orient.core.index.OClassIndexManager.onRecordBeforeCreate(OClassIndexManager.java:423)
	at com.orientechnologies.orient.core.hook.ODocumentHookAbstract.onTrigger(ODocumentHookAbstract.java:218)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:963)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1683)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:94)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2271)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1769)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1760)
	at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:304)
	at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:284)
	at com.tinkerpop.blueprints.impls.orient.OrientElement.setProperty(OrientElement.java:186)
	at com.orientechnologies.orient.etl.transformer.OVertexTransformer.executeTransform(OVertexTransformer.java:83)
	at com.orientechnologies.orient.etl.transformer.OAbstractTransformer.transform(OAbstractTransformer.java:37)
	at com.orientechnologies.orient.etl.OETLPipeline.execute(OETLPipeline.java:108)
	at com.orientechnologies.orient.etl.OETLProcessor.executeSequentially(OETLProcessor.java:483)
	at com.orientechnologies.orient.etl.OETLProcessor.execute(OETLProcessor.java:291)
	at com.orientechnologies.orient.etl.transformer.OVertexTransformerNGTest.testErrorOnDuplicateVertex(OVertexTransformerNGTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:641)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:667)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:840)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1141)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:137)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:121)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1108)
	at org.testng.TestRunner.privateRun(TestRunner.java:737)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:315)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:310)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:272)
	at org.testng.SuiteRunner.run(SuiteRunner.java:221)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1028)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:965)
	at org.testng.TestNG.run(TestNG.java:896)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:174)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
ETL process halted: com.orientechnologies.orient.etl.OETLProcessHaltedException: com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record Person{name:Gregor}: found duplicated key 'Gregor' in index 'Person.name' previously assigned to the record #11:0 RID=#11:0
Mar 26, 2015 9:00:23 PM com.orientechnologies.common.log.OLogManager log
WARNING: {db=EdgeTransformerTest} Requested command 'create vertex type 'Person' as subclass of 'V'' must be executed outside active transaction: the transaction will be committed and reopen right after it. To avoid this behavior execute it outside a transaction
Mar 26, 2015 9:00:23 PM com.orientechnologies.common.log.OLogManager log
WARNING: {db=EdgeTransformerTest} Requested command 'create key index on 'Vertex.name'' must be executed outside active transaction: the transaction will be committed and reopen right after it. To avoid this behavior execute it outside a transaction
BEGIN ETL PROCESSOR
END ETL PROCESSOR
+ extracted 4 rows (0 rows/sec) - 4 rows -> loaded 2 vertices (0 vertices/sec) Total time: 5ms [0 warnings, 0 errors]
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.923 sec

Results :

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.3.2:jar (default-jar) @ orientdb-etl ---
[INFO] Building jar: /home/stokito/workspace/orientdb-etl/target/orientdb-etl-2.0.3.jar
[INFO] 
[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ orientdb-etl ---
[INFO] Installing /home/stokito/workspace/orientdb-etl/target/orientdb-etl-2.0.3.jar to /home/stokito/.m2/repository/com/orientechnologies/orientdb-etl/2.0.3/orientdb-etl-2.0.3.jar
[INFO] Installing /home/stokito/workspace/orientdb-etl/pom.xml to /home/stokito/.m2/repository/com/orientechnologies/orientdb-etl/2.0.3/orientdb-etl-2.0.3.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.333s
[INFO] Finished at: Thu Mar 26 21:00:23 EET 2015
[INFO] Final Memory: 16M/209M
[INFO] ------------------------------------------------------------------------

Process finished with exit code 0
```

**Comment by lvca** [comment]
Fixed. @NathanielMichael please could you confirm this problem is gone in "develop" or "2.0.x" branch?
