### ISSUE TITLE
MERGE transformer broken

### ISSUE THREAD

**Issue by garrett-gottlieb** [orientechnologies/orientdb-etl#20]
The ETL seems to be getting stuck on MERGE:
```
    {
      "merge": {
        "joinFieldName": "objectId",
        "lookup": "OUser.objectId"
      }
    },
```

Here's the debug output:
```
[0:merge] DEBUG Transformer input: {settings:{__type=Pointer, className=Settings, objectId=CqMFvY5w6s},acceptedTerms:true,activitiesCount:1,appFirstUseDate:{__type=Date, iso=2013-06-28T04:47:46.649Z},birthday:{__type=Date, iso=1996-10-23T00:00:00.000Z},email: REMOVED,emailVerified:false,first_name:Valentina,followerCount:0,followingCount:0,gender:2,goal:1,height_unit:1,height_val2:70,homeEquipment:[1],kitchenSinkBadgesSeen:[4],level:1,numReferrals:0,postCount:1,seenHamburgerInstructions:true,stream:default,timezone:America/Bogota,unsubscribedFromWorkoutEmails:true,username:tintinagaviria,weight:54,weight_unit:2,createdAt:2013-06-28T04:50:35.717Z,updatedAt:2014-04-08T17:50:16.324Z,objectId:mYeA6ISbP6,ACL:{*={read=true}, mYeA6ISbP6={read=true, write=true}},sessionToken:15rrtfjp58x4wfsvct9wmicg9,weightUnit:2,firstName:Valentina,heightUnit:1,heightVal2:70}
Exception in thread "main" java.lang.NoSuchMethodError: com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getMetadata()Lcom/orientechnologies/orient/core/metadata/OMetadataDefault;
	at com.orientechnologies.orient.etl.transformer.OAbstractLookupTransformer.lookup(OAbstractLookupTransformer.java:79)
	at com.orientechnologies.orient.etl.transformer.OMergeTransformer.executeTransform(OMergeTransformer.java:46)
	at com.orientechnologies.orient.etl.transformer.OAbstractTransformer.transform(OAbstractTransformer.java:37)
	at com.orientechnologies.orient.etl.OETLPipeline.execute(OETLPipeline.java:108)
	at com.orientechnologies.orient.etl.OETLProcessor.executeSequentially(OETLProcessor.java:464)
	at com.orientechnologies.orient.etl.OETLProcessor.execute(OETLProcessor.java:257)
	at com.orientechnologies.orient.etl.OETLProcessor.main(OETLProcessor.java:225)
```

I'm using 2.0-M2

**Comment by garrett-gottlieb** [comment]
This seems to have disappeared.
