### ISSUE TITLE
Unable to import 4.5G GraphML file

### ISSUE THREAD

**Issue by iammayankg** [orientechnologies/orientdb-etl#71]
Hi, I get this error when trying to import graphml exported from neo4j.

Error: com.orientechnologies.orient.core.exception.OStorageException

Error: com.orientechnologies.orient.core.exception.OStorageException: Error during removal of mapping between logical and physical record position.

Error: com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.ONestedRollbackException: Atomic operation was rolled back by internal component
There were few errors initially due to heapsize which I got rid of by configuring the script. I am stalled on this one.

**Comment by lvca** [comment]
@iammayankg Do you have the full stack trace? Usually such internal errors are due to out of memory. How did you configure the JVM? What settings did you use to import it?

**Comment by iammayankg** [comment]
Hi, Here's the stacktrace
Importing GRAPHML database from database xxx.graphml...{db=xxx} Error on creating record in cluster: com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster@f5d240d
com.orientechnologies.orient.core.exception.OStorageException
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createRecord(OPaginatedCluster.java:444)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCreateRecord(OAbstractPaginatedStorage.java:1668)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:2152)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1016)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:596)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:148)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2549)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2518)
        at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:161)
        at com.orientechnologies.orient.graph.console.OGraphMLReader.inputGraph(OGraphMLReader.java:297)
        at com.orientechnologies.orient.graph.console.OGraphMLReader.inputGraph(OGraphMLReader.java:118)
        at com.orientechnologies.orient.graph.console.OGraphMLReader.inputGraph(OGraphMLReader.java:93)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.importDatabase(OGremlinConsole.java:119)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:382)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:247)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:136)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:65)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.ArrayDeque.<init>(Unknown Source)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALChangesTree.applyChanges(OWALChangesTree.java:248)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALChangesTree.getLongValue(OWALChangesTree.java:118)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALChangesTree$PointerWrapper.getLong(OWALChangesTree.java:788)
        at com.orientechnologies.common.serialization.types.OLongSerializer.deserializeFromDirectMemory(OLongSerializer.java:130)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getLongValue(ODurablePage.java:108)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedClusterState.getFreeListPage(OPaginatedClusterState.java:65)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.findFreePage(OPaginatedCluster.java:1528)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.addEntry(OPaginatedCluster.java:1476)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.createRecord(OPaginatedCluster.java:433)
        ... 20 more

Error: com.orientechnologies.orient.core.exception.OStorageException

Error: com.orientechnologies.orient.core.exception.OStorageException: Error during removal of mapping between logical and physical record position.

Error: com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.ONestedRollbackException: Atomic operation was rolled back by internal component

**Comment by iammayankg** [comment]
In server.sh I configured:
MAXHEAP=-Xmx1G
and
MAXDISKCACHE="-Dstorage.diskcache.buffersize=5200"

I imported it using the console command "Import graphml". Initially it threw a java lang memory/GC error, but after setting the configuration as mentioned on the OrientDB performance page those went away.

**Comment by lvca** [comment]
How much RAM do you have in that server? Could you also try setting `-Dstorage.useWAL=false` ?

**Comment by iammayankg** [comment]
Hi, The server has about 8G of free RAM. 

I tried disabling WAL and got the following error:

Importing GRAPHML database from database xxx.graphml...
Error: com.orientechnologies.orient.core.exception.OStorageException: WAL mode is not active. Transactions are not supported in given mode

If there is any recommended setting for the server I can consider that. My data is about 4.5G in GraphML format.

**Comment by lvca** [comment]
I've introduced a new param in importer: batchSize. Please use last 2.1-SNAPSHOT and take a look at: http://orientdb.com/docs/last/Import-from-Neo4j-into-OrientDB.html

**Comment by gg4u** [comment]
Hi @Ivca, I am running in the same problem. Testing Orientdb importer: IMPORT DATABASE /tmp/out.graphml batchSize=100 storeVertexIds=true : 

Importing GRAPHML database from /tmp/out.graphml with options (batchSize=*100* storeVertexIds=true)...
Error: java.lang.OutOfMemoryError: GC overhead limit exceeded using version 2.1.0

**Comment by lvca** [comment]
How much RAM are you using or OrientDB in terms of heap? How your vertices/edges are big? Have you tried to reduce the batchSize to 20 ?

**Comment by gg4u** [comment]
I will try reduce batch to 20; exported db is 16GB (in neo is 8GB? maybe another format). Where do I look for the RAM assigned in heap ? couldn't find in config/orientdb-server-config.xml

**Comment by lvca** [comment]
edit oetl.sh and change -Xmx512m to -Xmx2G

**Comment by gg4u** [comment]
nope, did not work out. maybe some issue in the db exported from neo? 
I would like to taste the difference, especially in lucene queries (find meaningful results to start a traversal). Maybe I should import the db from csv..

**Comment by lvca** [comment]
If you can send us your database, we can try importing it.

**Comment by gg4u** [comment]
it s 16 gb @lvca , i m trying with pyorient to reimport it.  it is an undirected graph, i also posted some questions about undirected graph on google discussion, might you have some time to clarify model to adopt respect the query i d like to use.

**Comment by robfrank** [comment]
hi @gg4u, did you resolve this issue using  pyOrient?

**Comment by lvca** [comment]
Closed because no response.
