### ISSUE TITLE
Datafile Path vars concatenation broken in odb214

### ISSUE THREAD

**Issue by simper66** [orientechnologies/orientdb-etl#99]
Hi,

The following way of generating the datafile path has stopped working for me in odb214. It works fine in odb21.

CMD>oetl.bat C:\Users\jorge\Desktop\odb214\databases\GEONAMES\loadContinents.json

loadContinents.json:

{
	"config": {
		"log": "INFO",
		"**fileDirectory**": "C:\\Users\\jorge\\Desktop\\odb21\\databases\\GEONAMES\\",
		"**fileName**": "GEO_CONTINENTS.txt"
	},
	"begin": [
		{
			"let": { 
				"name": "$filePath",  
				"expression": "**$fileDirectory.append($fileName)**"
			}
		}
	],
	"source" : {
		"file": { "path": "**$filePath**", "lock" : false }
	},
        .........

OrientDB etl v.2.1.4 (build @BUILD@) www.orientdb.com
Exception in thread "main" com.orientechnologies.orient.core.exception.OConfigurationException: Error on creating ETL processor
        at com.orientechnologies.orient.etl.OETLProcessor.parse(OETLProcessor.java:249)
        at com.orientechnologies.orient.etl.OETLProcessor.parse(OETLProcessor.java:159)
        at com.orientechnologies.orient.etl.OETLProcessor.parseConfigAndParameters(OETLProcessor.java:149)
        at com.orientechnologies.orient.etl.OETLProcessor.main(OETLProcessor.java:113)
Caused by: java.lang.NullPointerException
        at java.io.File.<init>(File.java:277)
        at com.orientechnologies.orient.etl.source.OFileSource.configure(OFileSource.java:77)
        at com.orientechnologies.orient.etl.OETLProcessor.configureComponent(OETLProcessor.java:470)
        at com.orientechnologies.orient.etl.OETLProcessor.parse(OETLProcessor.java:209)
        ... 3 more

Anyway it works if i simplify like this:

{
	"source": { 
		"file": { "path": "C:\Users\jorge\Desktop\odb214\databases\GEONAMES\GEO_CONTINENTS.txt" } 
	},

Enviroment:

OrientDB: OrientDB 2.1.4 GA Community Edition (October 13, 2015)
SO: Windows7
JDK: Jdk 1.8.0_45
OrientDB Configuration: No special configuration. The one out of the box.
Mode: Standalone. server.bat

**Comment by robfrank** [comment]
Hi, I fixed this issues, it will be avaliable on next 2.1.5 or you can build the end replace the orientdb-etl jar in your installation. https://github.com/orientechnologies/orientdb-etl/commit/1ad9a158fec5939b0f513fbc943a50c49b36fcd6
